---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{.Name}}
spec:
  description: Allow ingress traffic to reach pod
  endpointSelector:
    matchLabels:
      app: {{.Name}}
  ingress:
  - fromEndpoints:
    - matchLabels:
        io.cilium.k8s.policy.serviceaccount: envoy-contour
        io.kubernetes.pod.namespace: contour
    toPorts:
    - ports:
      - port: "8080"
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{.Name}}
spec:
  hostnames:
    - d2s.staging.platipy.io
  parentRefs:
    - name: contour
      namespace: contour
      sectionName: platipy-staging
  rules:
    - backendRefs:
        - kind: Service
          name: {{.Name}}
          port: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Name}}
  labels:
    app: {{.Name}}
spec:
  selector:
    app: {{.Name}}
  ports:
    - port: 8081
      targetPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: {{.Name}}
  labels:
    app: {{.Name}}
spec:
  containers:
    - command: ["/ktunnel/ktunnel", "server", "-p", "{{.Port}}"]
      image: docker.io/omrieival/ktunnel:v1.6.1
      name: {{.Name}}
