name: release
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 8
      fail-fast: false
      matrix:
        goos:
        - {name: darwin, suffix: ""}
        - {name: linux, suffix: ""}
        - {name: windows, suffix: ".exe"}
        goarch:
        - amd64
        - arm64
    env:
      CGO_ENABLED: "0"
      GOOS: ${{matrix.goos.name}}
      GOARCH: ${{matrix.goarch}}
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23
    - name: Generate Templates
      run: |
        GOOS=linux GOARCH=amd64 go install github.com/a-h/templ/cmd/templ@latest
        TEMPL_EXPERIMENT=rawgo ~/go/bin/templ generate
    - name: Build
      run: go build -ldflags '-s -w' -o d2s-${{matrix.goos.name}}-${{matrix.goarch}}${{matrix.goos.suffix}} *.go
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: d2s-*