name: releases
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  binary:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 8
      fail-fast: false
      matrix:
        goos:
        - {name: darwin, suffix: ""}
        - {name: linux, suffix: ""}
        - {name: windows, suffix: ".exe"}
        goarch:
        - amd64
        - arm64
    env:
      CGO_ENABLED: "0"
      GOOS: ${{matrix.goos.name}}
      GOARCH: ${{matrix.goarch}}
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23
    - name: Generate Templates
      run: |
        GOOS=linux GOARCH=amd64 go install github.com/a-h/templ/cmd/templ@latest
        TEMPL_EXPERIMENT=rawgo ~/go/bin/templ generate
    - name: Build
      run: go build -ldflags '-s -w' -o d2s-${{matrix.goos.name}}-${{matrix.goarch}}${{matrix.goos.suffix}} *.go
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: d2s-*

  image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io/ixday/d2s
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/ixday/d2s:latest,ghcr.io/ixday/d2s:${{ github.sha }}
          cache-from: type=registry,ref=ghcr.io/ixday/d2s:latest
          cache-to: type=registry,ref=ghcr.io/ixday/d2s:latest,mode=max
