name: tests
on:
  push:
  pull_request:

jobs:
  editorconfig:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Cache mise install
        id: cache-mise
        uses: actions/cache@v4
        env:
          cache-name: cache-mise
        with:
          path: ~/.local/share/mise
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/mise.toml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install mise tools
        run: |
          curl https://mise.run | MISE_INSTALL_PATH=/usr/local/bin/mise sh
          mise settings experimental=true
          mise install

      - name: Running editorconfig checker
        run: mise exec -- mrake test:editorconfig

  vulnerabilities:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: Cache mise install
        id: cache-mise
        uses: actions/cache@v4
        env:
          cache-name: cache-mise
        with:
          path: ~/.local/share/mise
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/mise.toml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install mise tools
        run: |
          curl https://mise.run | MISE_INSTALL_PATH=/usr/local/bin/mise sh
          mise settings experimental=true
          mise install

      - name: Running vulnerability test
        run: mise exec -- mrake test:vulnerability
